### ISSUE TITLE
file is missing

### ISSUE THREAD

**Issue by RongTimYeap** [vihoikka/Cas10_prober#1] opened 2024-04-08 20:43 UTC
Hi there,
I am trying to run this, but there is always an error when processing with " rule Cas10_genomes". It seems to me one file is missing, that is "cas10_db="/media/volume/st_andrews/cas10_corA_2/profiles/Profiles/all_cas10s.hmm"" Could you provide this file? Thank you!

Bing

**Comment by vihoikka** [comment] 2024-04-09 08:38
Hi Bing!

Thanks for letting me know. I've now added the missing Cas10 HMM library to the msa_050523 folder and updated the instructions. Please let me know if you have any further issues!

Ville

**Comment by RongTimYeap** [comment] 2024-04-11 14:13
Hi Ville,
Thank you for providing the profile with updated instructions. Such error was perfectly cleared, however new error comes out in "rule_concat_cluster_cas10_proteins". I checked the log file and project directory and found no directory of "064_cas10_clusters" was generated. Could you help me to fix that? Thank you! Please let me know if you need more information about the error.

Bing

**Comment by vihoikka** [comment] 2024-04-12 12:36
Snakemake usually deletes folders if a rule was unsuccessful, so that's probably why there's no data there. In this case, the run probably failed because the rule ```concat_cluster_cas10_proteins``` is trying to run cd-hit without a conda environment specification (I've probably had cd-hit installed in the conda environment that I use to run the Snakemake pipeline, so I've had no issues with this rule). I've now added a conda environment specification to this Snakemake rule, so it now uses the trees.yaml environment file which contains cd-hit. Let me know if this works and if you have any further issues 😊

Ville

**Comment by RongTimYeap** [comment] 2024-04-12 13:11
Thank you. The issue was solved by installing cd-hit. The next error is " rule type_iii_wildcarder" . It seems to me "python3 scripts/loci_wildcarder.py" fails to generate the output_folder: 071_cctyper_loci. Is it caused by python version? In our conda environment, the python3 is 3.12.2.

Bing

**Comment by vihoikka** [comment] 2024-04-12 13:40
The Python version is unlikely to be the issue here. This rule (or checkpoint) uses pandas, but again I had not determined a rule-specific conda environment and had instead relied on currently active conda environment which had pandas installed. So, my bad! I've now added the environment specification, let me know how it goes.

**Comment by RongTimYeap** [comment] 2024-04-12 15:52
Hi Ville,
Thank you for your quick response. I tried to add "conda: "envs/pandas.yaml"" in my cas10_prober.smk file as you did, unfortunately, the same error comes out. 
Bing

**Comment by vihoikka** [comment] 2024-04-15 09:00
Could you provide the error message that Snakemake outputs?

**Comment by RongTimYeap** [comment] 2024-04-15 13:24
That error was bypassed by deleting the line " conda: "envs/pandas.yaml" but instead install joblib in the environment. (Looks like pandas 1.5.2 is not compatible). The new error happens in rule cATyper_hmm. The log file is attached here. Please let me know if you could not see it.
[2024-04-14T133811.621377.snakemake.log](https://github.com/vihoikka/Cas10_prober/files/14979583/2024-04-14T133811.621377.snakemake.log)

**Comment by RongTimYeap** [comment] 2024-04-15 14:24
Here is another issue that I already solved by downgrading my python in the environment from 3.12 to 3.9 and adding two channels: conda-forge and bioconda in envs/CRISPRCasTyper.yaml. The issue is: " CreateCondaEnvironmentException:
Could not create conda environment from /scratch/users/bwang/software/Cas10_prober/envs/CRISPRCasTyper.yaml: "

Best,
Bing

**Comment by vihoikka** [comment] 2024-04-15 15:57
> That error was bypassed by deleting the line " conda: "envs/pandas.yaml" but instead install joblib in the environment. (Looks like pandas 1.5.2 is not compatible). The new error happens in rule cATyper_hmm. The log file is attached here. Please let me know if you could not see it. [2024-04-14T133811.621377.snakemake.log](https://github.com/vihoikka/Cas10_prober/files/14979583/2024-04-14T133811.621377.snakemake.log)

Ok, glad you got forward a bit! This log file indeed shows that the issue is with rule cATyper_hmm, but to actually see the error you should check the logs files of the individual rules that failed. For example `/scratch/users/yz16c/programs/Cas10_prober/run3/10_cATyper_hmm/logs/GCF_018517205.1_0.err`. In case this log file gets deleted upon the failed run, you can change the output path of these individual log files by modifying the rule's log paths to for example `/scratch/users/yz16c/programs/Cas10_prober/run3/logs/catyper_hmm`.

**Comment by vihoikka** [comment] 2024-04-15 15:59
> Here is another issue that I already solved by downgrading my python in the environment from 3.12 to 3.9 and adding two channels: conda-forge and bioconda in envs/CRISPRCasTyper.yaml. The issue is: " CreateCondaEnvironmentException: Could not create conda environment from /scratch/users/bwang/software/Cas10_prober/envs/CRISPRCasTyper.yaml: "
> 
> Best, Bing

Thank you for this info, I've now also updated that .yaml file.

**Comment by RongTimYeap** [comment] 2024-04-15 16:47
Thanks. Somehow I have fixed this issue of rule cATyper_hmm. The next error is in rule unknown_finder. It is caused by the missing file scripts/unknown_finder.py. Could you upload this file?  
"'
python3: can't open file '/scratch/users/bwang/software/Cas10_prober/scripts/unknown_finder.py': [Errno 2] No such file or directory
'"

Best,
Bing

**Comment by vihoikka** [comment] 2024-04-16 08:34
Thanks for your patience.

The unknown_finder rule is actually a left-over from a previous analysis which made its way into this pipeline. It is not needed to reproduce the analysis in the CorA paper. I've now commented out a couple of lines in the rule final, which makes it so that the unknown_finder rule is not run at all. If the pipeline works for you after this modification, I will remove the rule unknown rule completely in the next commit. Remember to change the paths in the rule final to fit your system.

Sorry for all the trouble – I should've tested the pipeline with a new machine myself first.

**Comment by RongTimYeap** [comment] 2024-04-16 15:09
Hi Ville, 
The pipeline works on my system now. I really appreciate all your guidance and time. I am still new on bioinformatic analysis. Could you please briefly tell me how do you plot such phylogenetic tree with these data?  In the final directory R/, there are four files, two .txt and two .tsv. Should I use all of them as input for plotting with ggtree or ggplot2? Forgive such naive questions. Thank you again.

Best,
Bing

**Comment by vihoikka** [comment] 2024-04-16 15:20
Very happy to hear you got it working 😊 You can use the R script in scripts/tree.R to recreate the tree in the paper. Modify the "project" variable and/or the paths below that in the R script to point to the R folder produced by the pipeline. Running the R script should generate the trees and save them as .png. You might need to uncomment some of the library installations in the start of the R script if doesn't work out of the box.

**Comment by vihoikka** [comment] 2024-04-19 13:11
I will close this issue now as completed. Feel free to open a new one if you have questions about the R part!

**Closed as completed by vihoikka** 2024-04-19 13:11 UTC
